trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: templates
      type: git
      name: Plumbing/core-templates
    - repository: proctorio-api-dotnet-client
      type: git
      name: Open/proctorio-api-dotnet-client

stages:
- template: stages/sync/azure-sync.yml@templates  # Template reference
  parameters:
    checkout: proctorio-api-dotnet-client
